---
- include_vars: default.yml
- include_vars: sec.yml
- include_vars: cfoutput.yml

- name: Stop rabbitmq app
  command: rabbitmqctl stop_app

- name: Join rabbitmq cluster
  shell: "echo {{ secondaryrelay }} | cut -d. -f1 | xargs -I^ rabbitmqctl join_cluster rabbit@^"

- name: Start rabbitmq app
  command: rabbitmqctl start_app

- name: Configure queue mirror
  command: rabbitmqctl -p mig set_policy mig-mirror-all "^(toschedulers|toagents|mig(|event))\." \'{"ha-mode":"all"}\'
