---
- include_vars: default.yml
- include_vars: sec.yml

- name: Install packages
  package:
    name: "{{ item }}"
  with_items:
    - rabbitmq-server

- name: Base rabbitmq configuration
  copy:
   src: rabbitmq.config
   dest: /etc/rabbitmq/rabbitmq.config
   mode: 0644
   owner: rabbitmq
  notify: Restart rabbitmq

- name: rabbitmq enabled_plugins
  copy:
    src: enabled_plugins
    dest: /etc/rabbitmq/enabled_plugins
    mode: 0644
    owner: rabbitmq
  notify: Restart rabbitmq

- name: Install CA certificate
  copy:
    content: "{{ internalca }}"
    dest: /etc/rabbitmq/ca.crt
    mode: 0644
    owner: rabbitmq
  notify: Restart rabbitmq

- name: Install relay certificate
  copy:
    content: "{{ relaycert }}"
    dest: /etc/rabbitmq/relay.crt
    mode: 0644
    owner: rabbitmq
  notify: Restart rabbitmq

- name: Install relay key
  copy:
    content: "{{ relaykey }}"
    dest: /etc/rabbitmq/relay.key
    mode: 0644
    owner: rabbitmq
  notify: Restart rabbitmq

- name: Copy erlang cookie
  copy:
    content: "{{ erlangcookie }}"
    dest: "/var/lib/rabbitmq/.erlang.cookie"
    owner: rabbitmq
    mode: 0600
  notify: Restart rabbitmq

- meta: flush_handlers

- name: Add mig vhost
  command: rabbitmqctl add_vhost mig

- name: Add scheduler user
  command: "rabbitmqctl add_user scheduler {{ rabbitmq_pass_scheduler }}"

- name: Configure scheduler user
  command: rabbiqmectl set_permissions -p mig scheduler "^(toagents|toschedulers|mig\.agt\..*)$" "^(toagents|mig\.agt\.(heartbeats|results))$" "^(toagents|toschedulers|mig\.agt\.(heartbeats|results))$"
