---
- name: Install packages
  package:
    name: "{{ item }}"
  with_items:
    - iptables
    - iptables-persistent

- name: Set NAT policy
  iptables:
    chain: POSTROUTING
    table: nat
    jump: MASQUERADE
    out_interface: eth0

- name: Enable forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
