---
region: us-west-2
availability_zone: us-west-2a
keys: "alm-keys"
ami_id: ami-2709bd47
state: present
env: dev
deployrepo: "https://github.com/ameihm0912/mig-deploy.git"

base_stack_id: "1"
base_stack_name: "mig-base-{{ base_stack_id }}"

app_stack_id: "1"
app_stack_name: "mig-app-{{ app_stack_id }}"
api_certificate_name: "migapitmp"
