---
region: us-west-2
keys: "alm-keys"
ami_id: ami-2709bd47
state: present
env: dev

base_stack_id: "1"
base_stack_name: "mig-base-{{ base_stack_id }}"

app_stack_id: "1"
app_stack_name: "mig-app-{{ app_stack_id }}"
