---
- hosts: localhost
  connection: local

  vars:
    noderole: "{{ lookup('file', '/etc/myrole') }}"

  roles:
    - { role: "gw", when: noderole == "gw" }
    - { role: "api", when: noderole == "api" }
