---
- hosts: localhost
  connection: local

  vars:
    noderole: "{{ lookup('file', '/etc/myrole') }}"

  vars_files:
    - "vars/sec.yml"

  roles:
    - { role: "users", tags: ["users"] }
    - { role: "gw", tags: ["gw"] }
    - { role: "api", tags: ["api"] }
    - { role: "relay", primary: true, tags: ["relay1"] }
    - { role: "relay", primary: false, tags: ["relay2"] }
    - { role: "scheduler", tags: ["scheduler"] }
    - { role: "selfservice", tags: ["selfservice"] }
    - { role: "td-agent", tags: ["td-agent"] }
