---
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - "../vars/default.yml"
    - "../vars/sec.yml"

  tasks:
  - name: Configure MIG RDS
    action: cloudformation
      stack_name="{{ rds_stack_name }}"
      state="{{ state }}"
      region="{{ region }}"
      template="../templates/rds.json"
    args:
      template_parameters:
        Environment: "{{ env }}"
        DBPassword: "{{ migdbpass }}"
        BaseStack: "{{ base_stack_name }}"
