---
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - "../vars/vars-{{ env }}.yml"

  tasks:
  - name: Configure MIG instance roles
    action: cloudformation
      stack_name="{{ role_stack_name }}"
      state="{{ state }}"
      region="{{ region }}"
      template="../templates/role.json"
    args:
      template_parameters:
        Environment: "{{ env }}"
        RoleName: "{{ migrolename }}"
        SopsS3ARN: "{{ sopss3arn }}"
